master:
  image: gettyimages/spark:1.6.0-hadoop-2.6
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    SPARK_CONF_DIR: /conf
    MASTER: spark://master:7077
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

worker:
  image: gettyimages/spark:1.6.0-hadoop-2.6
  command: /usr/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 1g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data

namenode:
  image: badele/debian-hadoop
  hostname: namenode
  volumes:
    - /docker_shared/debian-hadoop/namenode:/shared
  ports:
    - "8020:8020"
    - "50070:50070"
  command: hdfs namenode

datanode1:
  image: badele/debian-hadoop
  hostname: datanode1
  volumes:
    - /docker_shared/debian-hadoop/datanode1:/shared
  links:
    - namenode
  ports:
    - "5001:50075"
  command: hdfs datanode

datanode2:
  image: badele/debian-hadoop
  hostname: datanode2
  volumes:
    - /docker_shared/debian-hadoop/datanode2:/shared
  links:
    - namenode
  ports:
    - "5002:50075"
  command: hdfs datanode
